#+TITLE: Installing Cyanogenmod on ASUS Transformer TF701t
#+DATE: [2014-12-06 Sat 07:23]
#+DESCRIPTION: How to.
#+SETUPFILE: ~/org-pub/topics/setup.org

* Get ADB working

To get ADB working follow [[../htc-inspire-4g/index.org][the section for the HTC Insprire 4G]].  In summary:

- Make sure user is in =plugdev=
- Make sure =udev= rule added
- In the tablets Setting->About tap on build number 7 times to turn on dev mode.

For the =udev= rule append:

#+BEGIN_EXAMPLE
# cat <<EOF >> /etc/udev/rules.d/51-android.rules
SUBSYSTEM=="usb", ATTR{idVendor}=="0b05", MODE="0666", GROUP="plugdev"
EOF
#+END_EXAMPLE

The vendor ID is printed by =dmesg=.  It seems I had to do the following this time for udev to notice the change:

#+BEGIN_EXAMPLE
  # udevadm control --reload-rules
#+END_EXAMPLE

Finally:

#+BEGIN_EXAMPLE
  $ adb devices
  List of devices attached 
  DAOKCY081267    device
#+END_EXAMPLE

If it shows "offline" the tablet is waiting for acceptance.

* Follow Cyanogenmod 

http://wiki.cyanogenmod.org/w/Install_CM_for_tf701t

** Unlock

*THIS WIPES THE TABLET*

Direct download link to ASUS unlock app: http://dlm3cdnet.asus.com/pub/ASUS/EeePAD/TF701T/TF701T_Unlock.rar

#+BEGIN_EXAMPLE
  $ unrar x TF701T_Unlock.rar
  $ adb install TF701T_Unlock/0820-0954_SIGNED_UnLock_for_TF701_repart.apk 
  6500 KB/s (759132 bytes in 0.114s)
          pkg: /data/local/tmp/0820-0954_SIGNED_UnLock_for_TF701_repart.apk
  Success
#+END_EXAMPLE

Run the unlocker app.  Since I'm using two factor Google auth I had to go into the Google security settings and make an app-specific password.  Tablet reboots and says "unlocked".  Then loads to a "Welcome" page and initial setup process.  Uncheck all sync options since we are just going to wipe this again.  

Have to repeat the 7-tap to turn on developer mode and st USB debugging.

** Recovery

Link from CM page:

#+BEGIN_EXAMPLE
  $ wget http://droidbasement.com/asus/tf701t/recovery/recovery.img
  $ md5sum recovery.img 
  9acb1acc88588665a8a5a833f86964f8  recovery.img
  $ adb devices   # (check)
  $ adb reboot bootloader
  $ fastboot devices
  15C3E10090400000016FD8440	fastboot
  $ fastboot -i 0xb05 flash recovery recovery.img 
  target reported max download size of 643825664 bytes
  sending 'recovery' (6644 KB)...
  OKAY [  0.901s]
  writing 'recovery'...
  OKAY [  0.199s]
  finished. total time: 1.101s
  $ fastboot reboot
  rebooting...
  
  finished. total time: 30.223s
#+END_EXAMPLE

This still leaves me at "RCK/Android/Wipe" boot page.  Select RCK and this boots to recovery.

** Install CM

Download =f78cd49d0ec50632eaef5f2a961b232c=.

#+BEGIN_EXAMPLE
  $ wget http://download.cyanogenmod.org/get/jenkins/93585/cm-11-20141206-NIGHTLY-tf701t.zip
  $ md5sum cm-11-20141206-NIGHTLY-tf701t.zip 
  f78cd49d0ec50632eaef5f2a961b232c  cm-11-20141206-NIGHTLY-tf701t.zip
#+END_EXAMPLE

In Recovery, 

- do a backup just for fun, the tablet is generic stock at this point
- wipe data/factory reset
- install zip via sideload method

#+BEGIN_EXAMPLE
  $ adb sideload cm-11-20141206-NIGHTLY-tf701t.zip 
  sending: 'sideload'  100%    
#+END_EXAMPLE

Wait to get control of the Recovery menu back and "reboot system now".

Woot!  Another Cyanogenmod device is born.

** Google apps

Download =gapps-kk-20140606-signed.zip= md5sum =d840e20fba6f0e2b85d1aebe493a88fa= from torrent linked on CM wiki.

#+BEGIN_EXAMPLE
  $ adb push gapps-kk-20140606-signed.zip /sdcard/
  5692 KB/s (157694716 bytes in 27.051s)
  $ adb reboot recovery
#+END_EXAMPLE

Navigate to =install zip=, zip is in =/sdcard/0/=.

Reboot back into Android.



