* Links

- [[http://gstreamer.freedesktop.org/data/doc/gstreamer/head/manual/manual.pdf][manual.pdf]]
- [[http://www.jonobacon.org/2006/08/28/getting-started-with-gstreamer-with-python/][python bindings example (blog)]] with PyGtk included
- [[https://wiki.ubuntu.com/Novacut/GStreamer1.0][porting to GStreamer 1.0]] use python-gi not python-gst
- [[https://github.com/thaytan/aurena][aurena]] this seems to be billed as what I want to do and includes the idea of monitoring the current time and adapting the playback rate.

* Aurena

Fill =~/.config/aurena/playlist.txt= with one path to an audio file per line.  Apparently a blank line gets counted too so don't add those.  =~/.local/share/aurena/aurena.db= gets updated with info on what is found.

** Ubuntu

On Ubuntu 14.04 need [[https://github.com/GNOME/libsoup/commit/1c71cb223b00eaa5c776229d9e0312ba852ef87a][this commit of May 9, 2014]] libsoup which means at least 2.45.90.  

** RPi

The RPi is even older as it only has libsoup 2.38.1.  GStreamer is at 1.2.0.  [[http://permalink.gmane.org/gmane.comp.video.gstreamer.devel/43011][Here is some info on building GStreamer from source for RPi]] in a cross-compiling way.  [[http://93.93.130.214/forums/viewtopic.php?t=34250&p=600776][This thread]] has someone that saved us the trouble but for just 1.2.4.
#+BEGIN_EXAMPLE
  deb http://vontaene.de/raspbian-updates/ . main
#+END_EXAMPLE

There is also a =jessie= Rasbian distro which one can =dist-upgrade= to.  It has GStreamer 1.4.4. 

#+BEGIN_EXAMPLE
  pi@rpi ~ $ cat /etc/apt/sources.list
  deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi
  # Uncomment line below then 'apt-get update' to enable 'apt-get source'
  #deb-src http://mirror.ox.ac.uk/sites/archive.raspbian.org/archive/raspbian/ wheezy main contrib non-free rpi
  
  deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
#+END_EXAMPLE

I removed X11 server and LXDE related packages before doing a dist-upgrade.

** BBB

I was messing with Volumio for BBB so that's my starting point. It is already at Debian Jessie.  This is "real" Debian, not Raspbian.

#+BEGIN_EXAMPLE
   volumio@bbb:~$ cat /etc/apt/sources.list
   deb http://http.debian.net/debian jessie main non-free
   # deb-src http://http.debian.net/debian wheezy main non-free
#+END_EXAMPLE

In upgrading both, BBB is clearly faster than RPi.  Maybe the eMMC.

* More links

- http://developer.ridgerun.com/wiki/index.php/Introduction_to_network_streaming_using_GStreamer
- http://docs.gstreamer.com/display/GstSDK/Tutorials
- https://github.com/rubenrua/GstreamerCodeSnippets
