#+TITLE: SSH Tips and Tricks
#+DATE: [2014-06-12 Thu 10:41]
#+DESCRIPTION: Yet another list of ways to use and abuse SSH
#+SETUPFILE: ~/org-pub/topics/setup.org

* SFTP

**  Emacs TRAMP

Unfortunately, TRAMP [[http://www.emacswiki.org/emacs/TrampMode#toc27][doesn't support sftp]].

** GNOME/Nautilus

For drag-and-drop type functionality you can make the GNOME Nautilus file browser "see" an sftp server.

You can use the Gnome "Places->Connect to server" dialog to have Nautilus access an sftp site.  Simply choose type "SSH" and fill in the fields.

You can do this on an ad-hoc bases by typing "=sftp://user@server/path/= into the "Location" entry of any Nautilus file-system browser window.  Type =Ctrl-L= to get this entry.

You can make an icon on the desktop to capture this as well. Right-click on the desktop, "Create Launcher" and use type location.  Use the same =sftp://= URL in the "Location" field as above.

*** Caveats

 - apparently, folder-to-folder copies where both folders are on sftp fails.

** SSHFS

For regular POSIX =cd/ls= type access you can mount an sftp server with SSHFS.   Make sure your user is in the group =fuse=, make a mount point, mount it, use it, and unmount it like this example:

#+BEGIN_EXAMPLE
$ mkdir  ~/mnt/www/bviren
$ sshfs bviren@www.phy.bnl.gov:/ ~/mnt/www/bviren
$ ls ~/mnt/www/bviren
www.andy.bnl.gov  www.cosmo.bnl.gov  
www.phy.bnl.gov  www.throwe.bnl.gov
$ fusermount -u ~/mnt/www/bviren
#+END_EXAMPLE
