#+TITLE: This site.
#+DATE: [2014-03-02 Sun 15:02]
#+SUBTITLE: Using of Emacs, Org and Python to make a web site.
#+CATEGORY: Meta
#+SETUPFILE: ~/org-pub/topics/setup.org
#+TAGS: emacs,org,python,pelican,web
#+DESCRIPTION: This site is generated from Emacs Org-mode sources.  Over the years, it has evolved to use various systems.  How it is published is described.


This web site has evolved over time.  It is currently written with
Emacs [[Http://orgmode.org][org-mode]].  It's Org source is exported with [[https://github.com/brettviren/orgonpy][OrgOnPy]] and [[http://blog.getpelican.com/][Pelican]].
This topic contains notes on how this is done.

* Generalities

I use Emacs for producing pretty much all of my information "output".
Except for Email (and IRC), I use Org mode to manage pretty much all
my text-based (non-code) output.  The main content that this web site
exposes are "topics" which are formal(ish) notes (like this one) which
I produce to remind myself what I did and for the sake of anyone else
that may be interested.  I will sometimes revise topics after their
initial "publication".

** History

This site went through many iterations.  Below we go through them in reverse chronological order.

* Emacs and Org

My [[https://github.com/brettviren/dot-emacs][Emacs config]] is online.  The [[https://github.com/brettviren/dot-emacs/blob/master/init-org.el][Org initialization]] adds to the
=org-capture-templates= list so I can start a "[[http://orgmode.org/manual/Capture.html][capture]]" of a topic
with =C-c c b= or revisit an existing topic with =C-c c B=.  

Because a topic may include multiple files, I have this start a
sub-directory for each topic under my topics storage area
(=~/org-pub/topics=).

Each new topic is created using a [[https://github.com/brettviren/org-pub/blob/master/templates/topic-start.template][template]] which will cause Org to
prompt for various items used later including title, subtitle,
category, tags (note, not same as Org headline tags) as well as
automatically fill some things like the date stamp (interpreted as a
creation date).  It also sets a =SETUPFILE= which contains some
minimal, global Org setup.

During authoring I can get a preview of how things look by doing a
local export (eg, =C-c C-e l p= for PDF, =C-c C-e h h= for HTML).
This export is not what eventually turns into the web page.

* OrgOnPy

Unfortunately, I have never been able to fully grok Elisp and Python
is my preferred scripting language.  So that I may process content in
Org in non-trivial ways I have developed [[https://github.com/brettviren/orgonpy][OrgOnPy]].  It works by running
some Elisp which I did manage to write with a lot of help from the Org
mailing list to get the Org document as an =org-element= tree.  It
then breaks some of the circular references that exist in that tree
before using Emacs's =json= module to convert it to JSON.  OrgOnPy
provides an =org-element=-like tree representation which can then be
used to provide Python objects which are somewhat reminiscent of their
Elisp counterparts.

* Pelican

Pelican is a static site generator.  It is well designed with fairly
good layering and a plugin system.  HTML is generated from two paths:
the overall structure of the pages is determined by Jinja templates
driven by metadata while the "payload" content is directly converted
from the content source files.

It is the job of the "reader" layer to provide metadata and HTML
content.  The "reader" is an explicit layer in the Pelican design and
it comes with readers that support Markdown, rST and AsciiDoc.  One
may also provide the "reader" as a plugin which is what OrgOnPy does
to add support for source files in Org markup.  The [[https://github.com/brettviren/orgonpy/tree/master/pelican-plugin/orgonpy][OrgOnPy Pelican
reader]] is heavily inspired by [[https://github.com/getpelican/pelican-plugins/tree/master/org_reader][=org_reader=]] which is part of the
Pelican plugin collection.  OrgOnPy also provides a [[https://github.com/brettviren/orgonpy/tree/master/pelican-plugin/extract_toc][modified version
of the =extract_toc=]] plugin also from the Pelican plugin collection.

Pelican has a number of "themes" which provide for HTML structure and
CSS styling.  For the most part a theme is defined at a layer boundary
so that most themes can be interchanged without changes to the source
content files.  I made a [[./pelican-themes.org][a survey of Pelican themes]] ultimately
settling on [[https://github.com/talha131/pelican-elegant/][elegant]] as being closest in structure and functionality to
what I wanted.  Inevitably I wanted to tweak so I have lightly [[https://github.com/brettviren/org-pub/tree/master/pelican/site/themes/elegant][forked elegant]].

** Machinations

Create an environment for building the web site

#+BEGIN_EXAMPLE
  $ virtualenv venv
  $ source venv/bin/activate
  $ pip install pelican beautifulsoup4
#+END_EXAMPLE

Build the site

#+BEGIN_EXAMPLE
  $ cd ~/org-pub/pelican/site
  $ pelican
  $ (cd output && python -m pelican.server)
#+END_EXAMPLE

Content is held in =site/content/= and exists as either immediate
files or relative symlinks to sub-directories of =topics/=.

That build locally.  Deployment is done with the help of the Fabric file and goes like:

#+BEGIN_EXAMPLE
  $ pip install fabric
  $ 
#+END_EXAMPLE

* Links

There are other ways to use Org to make web pages.  Here are some I've looked at.

- http://www.seas.upenn.edu/~heqin/academic/sitecreation.html
- http://doc.norang.ca/org-mode.html
- http://www.nicolas-petton.fr/blog/blogging-with-org-mode.html
- http://stevenbagley.net/blog/blog-with-emacs-org-mode.html
- http://kerunix.com/blog-using-orgmode-and-pelican.html
- http://steckerhalter.co.vu/posts/blogging-with-org-mode.html
- http://justinlilly.com/emacs/orgmode_static_site_generator.html
