#+TITLE: Linux on the Orange Pi Plus Dev Board
#+SUBTITLE: Another dev board
#+CATEGORY: Hardware
#+TAGS: arm,lpc,linux
#+DATE: [2015-07-12 Sun 17:12]
#+DESCRIPTION: This holds notes on getting Linux running on the Orange Pi.
#+SETUPFILE: ~/org-pub/topics/setup.org

I ordered an Orange Pi Plus dev board from AliExpress to test for use as a [[http://github.com/brettviren/lpc][Little Projector Computer]].

* Introduction

** Ordering

This was the first time to order from AliExpress.  The source had
didn't have enough in the pipeline so had to ask for a one week delay.
Since nominally it takes about a month this was no biggie.  It arrived
fine and AliExpress shopping "experience" was not bad.  They even
notified me by email it was sitting in my mail box before I knew about
it.

** Initial boot

Cable it up, plug it in.  It boots to Android into an XBMC-like
interface and all in Chinese.  It's fairly easy to navigate the
Android Settings menus to find the English setting (look for the icon
of a white box with a black "A" about half-way down).  It connected to
the home WPA2 wifi no problem, found an open NFS share (oops) and was
able to play a video with no problem.

The "phone" identifies as model "dolphin", has Android 4.4.2, Linux
3.4.39.  Build by "steven" who is also who I dealt with when ordering
it.  What a one man shop!?  Processor type unknown.  It comes with
various Android apps, about half with a Chinese title but they are
mostly self explanatory.

* Linux

But enough of Android, I want "real" Linux and of the Debian flavor.  OPi has [[http://www.orangepi.org/Docs/SDcardinstallation.html][these instructions]] to follow.

** Prepare microSD card

Download from OPi's Google Drive (!) as linked in the instructions.  No checksums are given that I can see, but this is what I downloaded.

#+BEGIN_EXAMPLE
  $ ls -lh *.xz
  -rw-rw-r-- 1 bv bv 846M Jul 12 17:15 Lubuntu_1404_For_OrangePiplus_v0_8_0_.img.xz
  -rw-rw-r-- 1 bv bv 284M Jul 12 17:09 orangepi-plus-debian-server-card-v0.9.img.xz
  $ sha1sum *.xz
  05247aa7f9e09cde3c0de9c9f34f97fa01eb0d6a  Lubuntu_1404_For_OrangePiplus_v0_8_0_.img.xz
  db8ae191e4f7cf556efaf29e51fd83361d957d01  orangepi-plus-debian-server-card-v0.9.img.xz
  $ md5sum *.xz
  7d9fe5e2bfc06b266c62d4882b9bc106  Lubuntu_1404_For_OrangePiplus_v0_8_0_.img.xz
  68ca3fa0f766b1185a7ca12e274d7a50  orangepi-plus-debian-server-card-v0.9.img.xz
#+END_EXAMPLE

After running =unxz= on them.

#+BEGIN_EXAMPLE
  $ md5sum orangepi-plus-debian-server-card-v0.9.img 
  3c4fd92f8a16d165273f70950ff4c159  orangepi-plus-debian-server-card-v0.9.img
  6c1e205c05fdd50bd629d030673efe0dd48664cd  orangepi-plus-debian-server-card-v0.9.img
  $ ls -l orangepi-plus-debian-server-card-v0.9.img
  -rw-rw-r-- 1 bv bv 969932800 Jul 12 17:09 orangepi-plus-debian-server-card-v0.9.img

  $ ls -l Lubuntu_1404_For_OrangePiplus_v0_8_0_.img 
  -rw-rw-r-- 1 bv bv 3670016000 Jul 12 17:15 Lubuntu_1404_For_OrangePiplus_v0_8_0_.img
  $ md5sum Lubuntu_1404_For_OrangePiplus_v0_8_0_.img
  b07dfd045eb064910073226edf20541d  Lubuntu_1404_For_OrangePiplus_v0_8_0_.img
  $ sha1sum Lubuntu_1404_For_OrangePiplus_v0_8_0_.img
  5340fd6dfb8fafc5a4336288a8ac32f56322d61a  Lubuntu_1404_For_OrangePiplus_v0_8_0_.img

#+END_EXAMPLE

The instructions say to format the SD card, but since eventually the image is written directly to the main device this seem superfluous.

Stick an 8GB microSD card In the Thinkpad's memory slot:

#+BEGIN_EXAMPLE
  # dd bs=4M if=orangepi-plus-debian-server-card-v0.9.img of=/dev/mmcblk0 ; sync
  231+1 records in
  231+1 records out
  969932800 bytes (970 MB) copied, 127.03 s, 7.6 MB/s
  # dd bs=4M if=Lubuntu_1404_For_OrangePiplus_v0_8_0_.img of=/dev/mmcblk0 ; sync
  875+0 records in
  875+0 records out
  3670016000 bytes (3.7 GB) copied, 693.245 s, 5.3 MB/s

#+END_EXAMPLE

** Other images

The community behind Orange Pi is not large.  [[http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=342&extra=page%3D1][This forum post]] gives links to Debian Jessie and Ubuntu Vivid images (including MATE!).  They are for Orange Pi 2, not Plus.  There is an =update_boot.sh= script that updates to the Plus.  It does this by downloading a tar file from [[http://loboris.eu/boot_kernel.tar.gz][here]], unpacking it and copying to =/boot= which seems rather dicey.  It is meant to be run on the OPi+.

loboris says,
#+BEGIN_QUOTE
for testing OPI-PLUS, please download OPI_boot_kernels.tar.gz from Mega.
unpack and read update_boot_kernel.txt about how to update.
#+END_QUOTE

** Enlarging the image

While the SD card is still in the laptop, but after the image is written, do:

#+BEGIN_EXAMPLE
$ sudo fdisk /dev/mmcblk0
p
Device         Boot  Start     End Sectors  Size Id Type
/dev/mmcblk0p1       40960  124927   83968   41M 83 Linux
/dev/mmcblk0p2      124928 7167999 7043072  3.4G 83 Linux
d
2
n
p
2
124928
ENTER (default, full size)
w
#+END_EXAMPLE

Eject, reinsert, unmount.

#+BEGIN_EXAMPLE
$ sudo e2fsck -f /dev/mmcblk0p2
$ sudo resize2fs /dev/mmcblk0p2
resize2fs 1.42.12 (29-Aug-2014)
Resizing the filesystem on /dev/mmcblk0p2 to 1924864 (4k) blocks.
The filesystem on /dev/mmcblk0p2 is now 1924864 (4k) blocks long.
#+END_EXAMPLE

Eject, reinsert, observe 7.9GB, unmount.

** Booting SD card

Not much to go on but starting with the Lubuntu image, stick it into
the SD slot and power up.  Boost fast!  Boots into 1280x720.  Comes pre-configured with some WiFi in China and Chromium has some history in it!

* Building the image

From [[http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=342&extra=page%3D1][this post]] and [[https://mega.co.nz/#F!09cD2LhZ!xnhXgvAQk4tojR6bRyDFqA][mega link]].

#+BEGIN_QUOTE
Building the system

You can try to build Debian/Ubuntu for OrangePI yourself.

- Download my scripts package =make_linux.tar.gz= from Mega, unpack to empty directory.

- You will need running Ubuntu or Debian system (you can even run it on OrangePI).

- Before running the script install =debootstrap= and =qemu-user-static= packages.

- Read carefully and edit =params.sh= to adjust the parameters to your needs.

- Run =sudo create_image= to create Ubuntu system. I recommend to build to local directory, then you can run =image_from_dir= to transfer the system to sd card or image.
#+END_QUOTE

Here is params.sh
#+BEGIN_EXAMPLE
  UIMAGE="orange/uImage_OPI-PLUS"
  BL1="orange/boot0_sdcard_OPI-PLUS.fex"
  UBOOT="orange/u-boot_OPI-PLUS.fex"
  HOSTNAME="lpc"
  USER="lpc"
  ROOTPASS="lpc"
  USERPASS="lpc"
  _timezone="Etc/UTC"
  _timezone="US/Eastern"
  LANGUAGE="en"
  LANG="en_US.UTF-8"
  image_name=""
  _format="ext4"
  fatsize=40
  linuxsize=800
  distro="vivid"
  repo="http://ports.ubuntu.com/ubuntu-ports"
  _compress="yes"
  _boot_on_ext4="no"
#+END_EXAMPLE

Good passwords, huh?

#+BEGIN_EXAMPLE
  $ sudo ./create_image
#+END_EXAMPLE

Something during the process turned my Window+Arrow key binding in Sawfish from switching between WM desktops to switching between Linux consoles.

Ends up with this message:

#+BEGIN_EXAMPLE
  Instalation finished.

  Copy files from boot-vivid to SD Card boot partition
    e.g.  cp boot-vivid/* <path_to_sdcard_boot_mount>
    and rsync linux-vivid to SD Card ext4 partition.
    e.g. sudo rsync -r -t -p -o -g -x -v --progress --delete -l -H -D --numeric-ids -s /opt/bv/projects/orange-pi/make_linux/linux-vivid/ <path_to_sdcard_ext4_mount>/

  Or create SDCard image running:
    sudo ./image_from_dir linux-vivid <DEVICE|IMAGE>

  You can chroot into "linux-vivid" to make additional changes:
    sudo chroot linux-vivid /usr/bin/qemu-arm-static -cpu cortex-a9 /bin/bash


  ,************************************************************
  ,* AFTER BOOTING:                                           *
  ,* -------------------------------------------------------- *
  ,* To RESIZE LINUX partition to fill sd card run:           *
  ,*   sudo fs_resize                                         *
  ,* -------------------------------------------------------- *
  ,* To change the board type / update run:                   *
  ,*   sudo update_boot.sh                                    *
  ,* -------------------------------------------------------- *
  ,* To install desktop run:                                  *
  ,*   sudo install_lxde_desktop                              *
  ,*   or, for better-looking (vivid&jessie)                  *
  ,*   sudo install_mate_desktop                              *
  ,*   DON'T FORGET TO RESIZE SD CARD IF NECESSARY FIRST      *
  ,* -------------------------------------------------------- *
  ,* To configure your local settings use:                    *
  ,*   sudo dpkg-reconfigure tzdata                           *
  ,*   sudo dpkg-reconfigure keyboard-configuration           *
  ,*   sudo dpkg-reconfigure console-setup                    *
  ,*     # change your system's locale entries by modifying   *
  ,*     # the file /etc/default/locale (e.g. en_US.UTF-8)    *
  ,*     # then run:                                          *
  ,*   sudo locale-gen <your_locale> (e.g en_US.UTF-8)        *
  ,*   sudo dpkg-reconfigure locales                          *
  ,************************************************************
#+END_EXAMPLE 

#+BEGIN_EXAMPLE
  $ sudo cp install_mate_desktop linux-vivid/root/
  $ sudo cp update_boot.sh linux-vivid/root/
  $ sudo ./image_from_dir linux-vivid /dev/mmcblk0
  ...
  Formating fat partition ...
  ERROR formating fat partition.
#+END_EXAMPLE

Adding =set -x= shows:

#+BEGIN_EXAMPLE
  ++ echo 'Formating fat partition ...'
  Formating fat partition ...
  ++ mkfs -t vfat -F 32 -n BOOT /dev/mmcblk01
  ++ '[' 1 -ne 0 ']'
  ++ echo 'ERROR formating fat partition.'
  ERROR formating fat partition.
  ++ exit 0
#+END_EXAMPLE

Looks like it assumes =/dev/sdXN= type device names where this device is =/dev/mmcblk0pN=.  Instead of fixing the script, just write an image file first and flash that manually.

#+BEGIN_EXAMPLE
  $ sudo ./image_from_dir linux-vivid linux-vivid.img

  $ ls -ltr
  -rw-r--r--  1 root root  20971520 Jul 18 15:22 linux-vivid.img.imgu
  -rw-r--r--  1 root root  41943040 Jul 18 15:23 linux-vivid.img.img1
  -rw-r--r--  1 root root 734003200 Jul 18 15:23 linux-vivid.img.img2
  -rw-r--r--  1 root root 167212352 Jul 18 15:23 linux-vivid.img.img.xz
  -rw-r--r--  1 root root 796917760 Jul 18 15:23 linux-vivid.img.img
  -rw-r--r--  1 root root        54 Jul 18 15:28 linux-vivid.img.img.md5sum
  -rw-r--r--  1 root root        57 Jul 18 15:28 linux-vivid.img.img.xz.md5sum

  $ cat *.md5sum
  9f97b70f10614180e3dd1dd1419fe426  linux-vivid.img.img
  3cf38513957f720ddf5dd53f00bf94f8  linux-vivid.img.img.xz

  $ sudo dd bs=4M if=linux-vivid.img.img of=/dev/mmcblk0 ; sync
#+END_EXAMPLE

Looks like I didn't need to add the explicit =.img=.

Boots to an Ubuntu 15.04 Linux console login prompt!  Login via SSH/wire get nice warning to resize:

#+BEGIN_EXAMPLE
  $ ssh root@192.168.1.28
  ...
  root@lpc:~# fs_resize
  (reboot, log back in)
  root@lpc:~# df -hl /
  Filesystem      Size  Used Avail Use% Mounted on
  /dev/mmcblk0p2  7.3G  479M  6.5G   7% /

  root@lpc:~# fdisk -l

  Disk /dev/mmcblk0: 7.4 GiB, 7948206080 bytes, 15523840 sectors
  Units: sectors of 1 * 512 = 512 bytes
  Sector size (logical/physical): 512 bytes / 512 bytes
  I/O size (minimum/optimal): 512 bytes / 512 bytes
  Disklabel type: dos
  Disk identifier: 0x062475c6

  Device         Boot  Start      End  Sectors  Size Id Type
  /dev/mmcblk0p1       40960   122879    81920   40M  b W95 FAT32
  /dev/mmcblk0p2      122880 15522816 15399937  7.4G 83 Linux

#+END_EXAMPLE

What about the internal eMMC?
Seems like some [[http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=309&extra=&page=3][rancor]] in orange pi land due to "Steven" promising and failing.

#+BEGIN_EXAMPLE
  You can copy your burning firmware image into /home/orangepi/burn-image-to-emmc/
  sudo dd bs=4M if=xxx.img of=/dev/mmcblk1
  xxx.img is your burning firmware image,This need to wait 30 minutes.
  sudo dd if=u-boot-sun8iw7p1.bin of=/dev/mmcblk1 bs=1024 seek=16400
#+END_EXAMPLE

** Latest Lubuntu 0.9.0 image from Steven

This promises to allow writing to internal eMMC

#+BEGIN_EXAMPLE
  $ sudo dd bs=4M if=Lubuntu_1404_For_OrangePiplus_v0_9_0_.img of=/dev/mmcblk0 ; sync
  root@orangepi:~# fdisk -l

  WARNING: GPT (GUID Partition Table) detected on '/dev/mmcblk0'! The util fdisk doesn't support GPT. Use GNU Parted.


  Disk /dev/mmcblk0: 7948 MB, 7948206080 bytes
  4 heads, 16 sectors/track, 242560 cylinders, total 15523840 sectors
  Units = sectors of 1 * 512 = 512 bytes
  Sector size (logical/physical): 512 bytes / 512 bytes
  I/O size (minimum/optimal): 512 bytes / 512 bytes
  Disk identifier: 0x2b1c25d6

          Device Boot      Start         End      Blocks   Id  System
  /dev/mmcblk0p1           40960      124927       41984   83  Linux
  /dev/mmcblk0p2          124928    15522816     7698944+  83  Linux

  Disk /dev/mmcblk1: 7838 MB, 7838105600 bytes
  1 heads, 16 sectors/track, 956800 cylinders, total 15308800 sectors
  Units = sectors of 1 * 512 = 512 bytes
  Sector size (logical/physical): 512 bytes / 512 bytes
  I/O size (minimum/optimal): 512 bytes / 512 bytes
  Disk identifier: 0x00000000

          Device Boot      Start         End      Blocks   Id  System
  /dev/mmcblk1p1   *     4923392    15374335     5225472    b  W95 FAT32
  /dev/mmcblk1p2           73728      106495       16384    6  FAT16
  /dev/mmcblk1p3               1     4816896     2408448    5  Extended
  /dev/mmcblk1p5          106496      139263       16384   83  Linux
  /dev/mmcblk1p6          139264      172031       16384   83  Linux
  /dev/mmcblk1p7          172032     1744895      786432   83  Linux
  /dev/mmcblk1p8         1744896     1777663       16384   83  Linux
  /dev/mmcblk1p9         1777664     1843199       32768   83  Linux
  /dev/mmcblk1p10        1843200     3416063      786432   83  Linux
  /dev/mmcblk1p11        3416064     3448831       16384   83  Linux
  /dev/mmcblk1p12        3448832     3481599       16384   83  Linux
  /dev/mmcblk1p13        3481600     3514367       16384   83  Linux
  /dev/mmcblk1p14        3514368     3579903       32768   83  Linux
  /dev/mmcblk1p15        3579904     3612671       16384   83  Linux
  /dev/mmcblk1p16        3612672     4923391      655360   83  Linux

  Partition table entries are not in disk order

  Disk /dev/mmcblk1boot1: 4 MB, 4194304 bytes
  4 heads, 16 sectors/track, 128 cylinders, total 8192 sectors
  Units = sectors of 1 * 512 = 512 bytes
  Sector size (logical/physical): 512 bytes / 512 bytes
  I/O size (minimum/optimal): 512 bytes / 512 bytes
  Disk identifier: 0x00000000

  Disk /dev/mmcblk1boot1 doesn't contain a valid partition table

  Disk /dev/mmcblk1boot0: 4 MB, 4194304 bytes
  4 heads, 16 sectors/track, 128 cylinders, total 8192 sectors
  Units = sectors of 1 * 512 = 512 bytes
  Sector size (logical/physical): 512 bytes / 512 bytes
  I/O size (minimum/optimal): 512 bytes / 512 bytes
  Disk identifier: 0x00000000

  Disk /dev/mmcblk1boot0 doesn't contain a valid partition table

#+END_EXAMPLE

Unmount all that and copy the Ubuntu Vivid image I made over to the running OPi.

#+BEGIN_EXAMPLE
  root@orangepi:/root# scp bv@hal:/home/bv/projects/orange-pi/make_linux/linux-vivid.img.img .
  root@orangepi:/root# dd bs=4M if=linux-vivid.img.img of=/dev/mmcblk1 ; sync
  root@orangepi:~/burn-image-to-emmc# dd if=u-boot-sun8iw7p1.bin of=/dev/mmcblk1 bs=1024 seek=16400
#+END_EXAMPLE

The =.bin= is in =/home/orangepi/burn-image-to-emmc/u-boot-sun8iw7p1.bin=.

#+BEGIN_EXAMPLE
  root@orangepi:~# fdisk -l /dev/mmcblk1

  Disk /dev/mmcblk1: 7838 MB, 7838105600 bytes
  4 heads, 16 sectors/track, 239200 cylinders, total 15308800 sectors
  Units = sectors of 1 * 512 = 512 bytes
  Sector size (logical/physical): 512 bytes / 512 bytes
  I/O size (minimum/optimal): 512 bytes / 512 bytes
  Disk identifier: 0x062475c6

          Device Boot      Start         End      Blocks   Id  System
  /dev/mmcblk1p1           40960      122879       40960    b  W95 FAT32
  /dev/mmcblk1p2          122880     1556480      716800+  83  Linux
#+END_EXAMPLE

Reboot with SD card removed.  Success!  Do =fs_resize= and reboot again.

#+BEGIN_EXAMPLE
  root@lpc:~# ./install_mate_desktop 
  ...
  usermod: user 'orangepi' does not exist
  chown: invalid user: 'orangepi:orangepi'
  ...
  ,**********************************************
  ,* MATE DESKTOP INSTALLED, please REBOOT now! *
  ,**********************************************
  root@lpc:~# reboot
#+END_EXAMPLE

MATE, but it is 720p.

Steven [[http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=337][says]] 
#+BEGIN_EXAMPLE
Third you copy script.bin to your MicroSD card boot partition /dev/sdb1 or /dev/mmcblk0p1
#+END_EXAMPLE

This is refering to what comes on the first partition of the Lubuntu 0.9.0 image.

#+BEGIN_EXAMPLE
  root@lpc:~# mount /dev/mmcblk0p1 /mnt
  root@lpc:~# ls -la /mnt/
  total 7847
  drwxr-xr-x  2 lpc  lpc      512 Dec 31  1969 .
  drwxr-xr-x 20 root root    4096 Jul 18 17:29 ..
  -rw-r--r--  1 lpc  lpc  8029912 Jul 18  2015 uImage
  root@lpc:~# scp bv@hal:/media/bv/F875-EAED/script.bin /mnt/
  root@lpc:~# reboot
#+END_EXAMPLE

Still looks 720p.  Try =update_boot.sh=

#+BEGIN_EXAMPLE
root@lpc:~# ./update_boot.sh 

Sat Jul 18 18:07:51 EDT 2015
************************************
Updating boot0 & u-boot for OrangePI
************************************

Do you want to download boot&kernel package from server, (y/N)?  y.
Downloading the package ...
--2015-07-18 18:07:53--  http://loboris.eu/boot_kernel.tar.gz
Resolving loboris.eu (loboris.eu)... 82.196.4.208
Connecting to loboris.eu (loboris.eu)|82.196.4.208|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16788502 (16M) [application/x-gzip]
Saving to: '/tmp/boot_kernel/boot_kernel.tar.gz'

/tmp/boot_kernel/boot_kernel. 100%[=================================================>]  16.01M  5.24MB/s   in 3.1s   

2015-07-18 18:07:57 (5.24 MB/s) - '/tmp/boot_kernel/boot_kernel.tar.gz' saved [16788502/16788502]

Unpacking ...
'./boot0_sdcard_OPI-2.fex' -> '/boot/boot0_sdcard_OPI-2.fex'
'./boot0_sdcard_OPI-PLUS.fex' -> '/boot/boot0_sdcard_OPI-PLUS.fex'
'./u-boot_OPI-2.fex' -> '/boot/u-boot_OPI-2.fex'
'./u-boot_OPI-PLUS.fex' -> '/boot/u-boot_OPI-PLUS.fex'
'./uImage_OPI-2' -> '/boot/uImage_OPI-2'
'./uImage_OPI-PLUS' -> '/boot/uImage_OPI-PLUS'
Files unpacked to /boot
=======================


==============================================
Select the OrangePI board you want to upgrade:
  1   OrangePI 2
  2   OrangePI PLUS
?  2.

Updating OrangePI PLUS

WARNING: boot0 & u-boot on /dev/mmcblk0 WILL BE REPLACED, Continue (y/N)?  y
Writing boot files to /dev/mmcblk0 ...
32+0 records in
32+0 records out
32768 bytes (33 kB) copied, 0.00152654 s, 21.5 MB/s
880+0 records in
880+0 records out
901120 bytes (901 kB) copied, 0.138017 s, 6.5 MB/s

Boot files updated, please REBOOT.
==================================

Do you want to write the new kernel (uImage) to fat partition (y/N)?  y
./update_boot.sh: line 116: [: /media/lpc/BOOT: binary operator expected
cp: target '/mnt/uImage' is not a directory

uImage updated, please REBOOT.
==============================

root@lpc:~# reboot
#+END_EXAMPLE

Survey says....   Errr....  Black screen.  No ping.  Red led.

Oh, wait, there was a script failure.  Dammit.

Reboot Lubuntu. 

#+BEGIN_EXAMPLE
  root@orangepi:/root# dd bs=4M if=linux-vivid.img.img of=/dev/mmcblk1 ; sync
  root@orangepi:~/burn-image-to-emmc# dd if=u-boot-sun8iw7p1.bin of=/dev/mmcblk1 bs=1024 seek=16400
#+END_EXAMPLE

This time read loboris more carefully:

#+BEGIN_QUOTE
All images are pepared for 1920x108p resolution.
To easily change resolution please download scripts_bin.zip from Mega, unpack and copy the file whitch matches your bord and resolution to SD Card FAT partition (where the uImage is).
Rename it to script.bin
#+END_QUOTE


#+BEGIN_EXAMPLE
  root@lpc:~# mount /dev/mmcblk0p1 /mnt
  root@lpc:~# ls -la /mnt
  total 7847
  drwxr-xr-x  2 root root     512 Dec 31  1969 .
  drwxr-xr-x 20 root root    4096 Jul 18 18:24 ..
  -rwxr-xr-x  1 root root 8029912 Jul 18  2015 uImage
  root@lpc:~# scp bv@hal:/home/bv/projects/orange-pi/script.bin.OPI-PLUS /mnt/script.bin
  root@lpc:~# md5sum /mnt/*
  df8ec789eb1df1f6dba0f8f337f7d547  /mnt/script.bin
  9489dd3a1a498b529948f4eb62210663  /mnt/uImage
  root@lpc:~# umount /mnt
  root@lpc:~# reboot
#+END_EXAMPLE

Seems to hang after:
#+BEGIN_EXAMPLE
disp_device_attached_and_enable,line:159:attched ok, mgr0<-->device0, type=4, mode=10
#+END_EXAMPLE

Note, =attched= is sic.  No network. I plug/unplug USB and get notice on the console.

Plugging in microSD card, and the boot continues!  And into 1080p.  WTF?

#+BEGIN_EXAMPLE
  root@orangepi:~# mount /dev/mmcblk0p1 /mnt/tmp/
  root@orangepi:~# ls -la /mnt/tmp/
  total 4982
  drwx------  3 orangepi orangepi   16384 Jan  1  1970 .
  drwxr-xr-x 19 root     root        4096 Jul 19 05:20 ..
  -rw-r--r--  1 orangepi orangepi   37468 Jun 21 22:30 script.bin
  drwx------  4 orangepi orangepi    2048 Jun 21 23:03 .Trash-1001
  -rw-r--r--  1 orangepi orangepi 5039512 Jun 21 19:59 uImage
  root@orangepi:~# md5sum /mnt/tmp/*
  849026298671c6bdb2377772a005898a  /mnt/tmp/script.bin
  d54037796857553115e3a2ba0ab828be  /mnt/tmp/uImage
#+END_EXAMPLE

Reboot with uSD card in to see eMMC.  Now, have 720p.

I think what's happening is that the =script.bin= from loboris is configured to use.  Remove =script.bin=.

#+BEGIN_EXAMPLE
root@orangepi:~# mount /dev/mmcblk1p1 /mnt/
root@orangepi:~# rm /mnt/tmp/script.bin 
#+END_EXAMPLE

Back in loboris's, redo:

#+BEGIN_EXAMPLE
  root@lpc:~# ./update_boot.sh 

  Sat Jul 18 18:52:35 EDT 2015
  ,************************************
  Updating boot0 & u-boot for OrangePI
  ,************************************

  Do you want to download boot&kernel package from server, (y/N)?  y.
  Downloading the package ...
  --2015-07-18 18:52:38--  http://loboris.eu/boot_kernel.tar.gz
  Resolving loboris.eu (loboris.eu)... 82.196.4.208
  Connecting to loboris.eu (loboris.eu)|82.196.4.208|:80... connected.
  HTTP request sent, awaiting response... 200 OK
  Length: 16788502 (16M) [application/x-gzip]
  Saving to: '/tmp/boot_kernel/boot_kernel.tar.gz'

  /tmp/boot_kernel/boot_kernel. 100%[=================================================>]  16.01M  5.19MB/s   in 3.1s   

  2015-07-18 18:52:42 (5.19 MB/s) - '/tmp/boot_kernel/boot_kernel.tar.gz' saved [16788502/16788502]

  Unpacking ...
  './boot0_sdcard_OPI-2.fex' -> '/boot/boot0_sdcard_OPI-2.fex'
  './boot0_sdcard_OPI-PLUS.fex' -> '/boot/boot0_sdcard_OPI-PLUS.fex'
  './u-boot_OPI-2.fex' -> '/boot/u-boot_OPI-2.fex'
  './u-boot_OPI-PLUS.fex' -> '/boot/u-boot_OPI-PLUS.fex'
  './uImage_OPI-2' -> '/boot/uImage_OPI-2'
  './uImage_OPI-PLUS' -> '/boot/uImage_OPI-PLUS'
  Files unpacked to /boot
  =======================


  ==============================================
  Select the OrangePI board you want to upgrade:
    1   OrangePI 2
    2   OrangePI PLUS
  ?  2.

  Updating OrangePI PLUS

  WARNING: boot0 & u-boot on /dev/mmcblk0 WILL BE REPLACED, Continue (y/N)?  y
  Writing boot files to /dev/mmcblk0 ...
  32+0 records in
  32+0 records out
  32768 bytes (33 kB) copied, 0.00311417 s, 10.5 MB/s
  880+0 records in
  880+0 records out
  901120 bytes (901 kB) copied, 0.118625 s, 7.6 MB/s

  Boot files updated, please REBOOT.
  ==================================

  Do you want to write the new kernel (uImage) to fat partition (y/N)?  y

  uImage updated, please REBOOT.
  ==============================

  root@lpc:~# reboot
#+END_EXAMPLE

No error this time....  Just black screen, Red LED power, screen lit, not ping, no keyboard light up.

One more time in Stevens.

#+BEGIN_EXAMPLE
  root@orangepi:/root# dd bs=4M if=/root/linux-vivid.img.img of=/dev/mmcblk1 ; sync
  root@orangepi:/root# dd if=/home/orangepi/burn-image-to-emmc/u-boot-sun8iw7p1.bin of=/dev/mmcblk1 bs=1024 seek=16400
  root@orangepi:/root# mount /dev/mmcblk1p1 /mnt
  root@orangepi:/root# mkdir /mnt/emmc-boot /mnt/sdcard-boot
  root@orangepi:/root# mount /dev/mmcblk1p1 /mnt/emmc-boot
  root@orangepi:/root# mount /dev/mmcblk0p1 /mnt/sdcard-boot
  root@orangepi:/root# ls -l /mnt/emmc-boot/ /mnt/sdcard-boot/
  /mnt/emmc-boot/:
  total 7842
  -rwxr-xr-x 1 root root 8029912 Jul 18 19:23 uImage

  /mnt/sdcard-boot/:
  total 4960
  -rwxr-xr-x 1 root root       0 Jul 19 06:59 FS.sd-boot
  -rwxr-xr-x 1 root root   37468 Jun 21 22:30 script.bin
  -rwxr-xr-x 1 root root 5039512 Jun 21 19:59 uImage

  root@orangepi:/root# cp /mnt/sdcard-boot/script.bin /mnt/emmc-boot/
  root@orangepi:/root# reboot
#+END_EXAMPLE

Boots.  Do =fs_resize=, reboot. install mate desktop.  Again, now =mmcblk0= is eMMC.  I guess the number is dynamically chosen.  Here are the md5sum of the booted kernel and script:

#+BEGIN_EXAMPLE
  root@lpc:~# md5sum /mnt/*
  849026298671c6bdb2377772a005898a  /mnt/script.bin
  9489dd3a1a498b529948f4eb62210663  /mnt/uImage
#+END_EXAMPLE

Arg, after installing MATE boots to lightdm but it's still 720p.  Next I can try writing Steven's uboot+script.

* Understanding u-boot/sunxi

- [[https://raw.githubusercontent.com/vonfritz/sunxi-boards/H3/sys_config/H3/orange_pi_plus.fex][fex file]]
- [[http://linux-sunxi.org/Xunlong_Orange_Pi_Plus][OPP page]]

Woot! 1080p.   Copy =script.bin= from boot partition and:

#+BEGIN_EXAMPLE
  root@lpc:~# cp /mnt/emmc-boot/script.bin .
  root@lpc:~# bin2fex script.bin script.fex
  fexc-bin: script.bin: version: 37468.1.2
  fexc-bin: script.bin: size: 37468 (79 sections)
  root@lpc:~# cp script.fex script-1080p.fex
  root@lpc:~# emacs -nw script-1080p.fex
  root@lpc:~# diff script.fex script-1080p.fex
  329c329
  < screen0_output_mode = 5
  ---
  > screen0_output_mode = 10
  351c351
  < :       If set gamc_phy to use = 1
  ---
  > ;:       If set gamc_phy to use = 1
  root@lpc:~# fex2bin script-1080p.fex script-1080p.bin
  root@lpc:~# cp script-1080p.bin /mnt/emmc-boot/script.bin
  root@lpc:~# reboot
#+END_EXAMPLE

