#+TITLE: Scope out my new i7 PC
#+DATE: [2014-06-28 Sat 19:40]
#+DESCRIPTION: This holds various things about my i7 machine.
#+SETUPFILE: ~/org-pub/topics/setup.org
#+CATEGORY: hardware

After a long time using ever aging computers at home I built a new workstation.

* Specs

- OS :: Ubuntu 15.04
- mobo :: [[http://www.newegg.com/Product/Product.aspx?Item=N82E16813157500][ASRock Z97 Extreme6]] (10 SATA)
- CPU :: [[http://www.newegg.com/Product/Product.aspx?Item=N82E16819116901][i7-4770K at 3.5GHz]]
- RAM :: [[http://www.newegg.com/Product/Product.aspx?Item=N82E16820231560][2x8GB G.SKILL Ares 240-pin DDR3]] (two slots still available)
- GPU :: [[http://www.newegg.com/Product/Product.aspx?Item=N82E16814487024][EVGA 02G-P4-3753-KR GeForce GTX 750 Ti Superclocked]]
- case :: [[http://www.newegg.com/Product/Product.aspx?Item=N82E16811139022][Corsair Carbide Air 540 Black]]
- HDD :: 2x [[http://www.newegg.com/Product/Product.aspx?Item=N82E16822148844][Seagate Barracuda 7200.14 ST3000DM001 3TB]]
- SDD :: [[http://www.newegg.com/Product/Product.aspx?Item=N82E16820171646][SanDisk SDSSDP-128G-G25]]
- PS :: [[http://www.newegg.com/Product/Product.aspx?Item=N82E16817139058][CORSAIR CSM CS450M 450W]]

Total cost was just over 1.1k.

* Some benchmarking
** Compare Building ROOT on SSD and HDD

- SSD :: 
- HDD :: Seagate

*** Download speed.

Obviously dominated by network.

#+BEGIN_EXAMPLE
hdd$ time wget ftp://root.cern.ch/root/root_v5.34.18.source.tar.gz
real	1m3.200s
user	0m0.325s
sys	0m1.368s

ssd$ time wget ftp://root.cern.ch/root/root_v5.34.18.source.tar.gz
real	1m1.630s
user	0m0.313s
sys	0m1.325s
#+END_EXAMPLE

*** Unpack

#+BEGIN_EXAMPLE
hdd$ sync; sync; sync
hdd$ time (tar -xvf root_v5.34.18.source.tar.gz ; sync)
real	0m2.664s
user	0m0.995s
sys	0m0.318s


ssd$ sync; sync; sync
ssd$ time (tar -xvf root_v5.34.18.source.tar.gz ; sync)
real	0m1.894s
user	0m0.982s
sys	0m0.314s
#+END_EXAMPLE

Trying this a second time shows these times are probably good to the first decimal place.

*** Configure

Prepare the OS with the slew of build dependencies:

#+BEGIN_EXAMPLE
$ sudo apt-get build-dep root-system 
$ sudo apt-get install cmake
#+END_EXAMPLE

Configure using CMake:

#+BEGIN_EXAMPLE
both$ mkdir build 
both$ cd build
#+END_EXAMPLE

#+BEGIN_EXAMPLE
hdd$ sync; sync; sync
hdd$ time cmake ../root -DCMAKE_INSTALL_PREFIX=../install 
real	0m3.530s
user	0m2.707s
sys	0m0.567s

hdd$ sync; sync; sync
hdd$ time cmake ../root -DCMAKE_INSTALL_PREFIX=../install 
real	0m3.284s
user	0m2.773s
sys	0m0.590s
#+END_EXAMPLE

*** Build

Serial make.  This fails at 71% in =libAfterImage=, so just for timing purposes:

#+BEGIN_EXAMPLE
hdd$ time make
real	18m19.952s
user	17m57.504s
sys	0m53.928s

ssd$ time make
real	18m19.203s
user	17m56.957s
sys	0m53.906s
#+END_EXAMPLE

Well, that's underwhelming.

** Building ROOT v6

#+BEGIN_EXAMPLE
$ time make -j 8
real	13m39.561s
user	97m52.141s
sys	4m17.270s

$ time make install
real	0m4.192s
user	0m2.594s
sys	0m1.592s
#+END_EXAMPLE

