def options(opt):
    opt.add_option('-x','--extra',action='store', 
                   help='Add something extra from the command line')

def chirp(ctx):
    print ('The little bit of extra is: "%s"' % ctx.options.extra)
